// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: envsight.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentUuid string                 `protobuf:"bytes,1,opt,name=agent_uuid,json=agentUuid,proto3" json:"agent_uuid,omitempty"` // Empty on first registration; cached UUID otherwise
	HostInfo  *HostInfo              `protobuf:"bytes,2,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`    // Static host inventory collected at startup
	// The credential this agent is presenting, also sent as gRPC Bearer
	// metadata. It is one of two things, and the server tells them apart by
	// their prefix:
	//
	//	an enrolment token   handed out by "Add Server", single-use and
	//	                     short-lived, naming the group the machine joins
	//	a machine credential issued by the server in the response below, and
	//	                     thereafter the only thing this agent presents
	//
	// A machine that has been enrolled sends the second. Only a machine that
	// has never registered — or one whose record was deleted — has anything to
	// do with the first.
	Token         string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_envsight_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentUuid() string {
	if x != nil {
		return x.AgentUuid
	}
	return ""
}

func (x *RegisterRequest) GetHostInfo() *HostInfo {
	if x != nil {
		return x.HostInfo
	}
	return nil
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentUuid string                 `protobuf:"bytes,1,opt,name=agent_uuid,json=agentUuid,proto3" json:"agent_uuid,omitempty"` // Server-issued or confirmed UUID
	Success   bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message   string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Error description when success == false
	// The machine's own long-lived credential, returned exactly once: on the
	// registration that enrolled it. Absent on every later registration,
	// because the agent already holds it.
	//
	// This is what moves identity off the enrolment token. That token names a
	// group, and a group is a fact that changes — a machine can be transferred
	// between them — so a credential carrying one goes stale the moment it
	// does. This credential names the machine and nothing else, which is the
	// one fact about it that never changes.
	//
	// `optional`, because proto3 cannot otherwise distinguish "the server did
	// not issue one" from "the server issued an empty string". An agent that
	// treats the second as the first would overwrite a working credential with
	// nothing and never reconnect.
	AgentCredential *string `protobuf:"bytes,4,opt,name=agent_credential,json=agentCredential,proto3,oneof" json:"agent_credential,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_envsight_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAgentUuid() string {
	if x != nil {
		return x.AgentUuid
	}
	return ""
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAgentCredential() string {
	if x != nil && x.AgentCredential != nil {
		return *x.AgentCredential
	}
	return ""
}

// HostInfo carries the static, rarely-changing facts about a machine.
type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsInfo        string                 `protobuf:"bytes,2,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Optional cloud provider instance ID
	CpuCores      int32                  `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemTotalMb    uint64                 `protobuf:"varint,5,opt,name=mem_total_mb,json=memTotalMb,proto3" json:"mem_total_mb,omitempty"`
	DiskTotalMb   uint64                 `protobuf:"varint,6,opt,name=disk_total_mb,json=diskTotalMb,proto3" json:"disk_total_mb,omitempty"`
	Gpus          []*GpuInfo             `protobuf:"bytes,7,rep,name=gpus,proto3" json:"gpus,omitempty"`
	CloudProvider string                 `protobuf:"bytes,8,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	// Swap capacity. Static, so it belongs with the rest of the inventory
	// rather than being repeated on every heartbeat beside swap_used_mb.
	SwapTotalMb   *uint64 `protobuf:"varint,9,opt,name=swap_total_mb,json=swapTotalMb,proto3,oneof" json:"swap_total_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_envsight_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{2}
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetOsInfo() string {
	if x != nil {
		return x.OsInfo
	}
	return ""
}

func (x *HostInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HostInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HostInfo) GetMemTotalMb() uint64 {
	if x != nil {
		return x.MemTotalMb
	}
	return 0
}

func (x *HostInfo) GetDiskTotalMb() uint64 {
	if x != nil {
		return x.DiskTotalMb
	}
	return 0
}

func (x *HostInfo) GetGpus() []*GpuInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *HostInfo) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

func (x *HostInfo) GetSwapTotalMb() uint64 {
	if x != nil && x.SwapTotalMb != nil {
		return *x.SwapTotalMb
	}
	return 0
}

// NodeState is the dynamic per-heartbeat payload streamed by the agent.
type NodeState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentUuid      string                 `protobuf:"bytes,1,opt,name=agent_uuid,json=agentUuid,proto3" json:"agent_uuid,omitempty"`
	Metrics        *Metrics               `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Ports          []*PortInfo            `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	Gpus           []*GpuInfo             `protobuf:"bytes,4,rep,name=gpus,proto3" json:"gpus,omitempty"` // GPU usage may change dynamically
	HasPhysicalTty bool                   `protobuf:"varint,5,opt,name=has_physical_tty,json=hasPhysicalTty,proto3" json:"has_physical_tty,omitempty"`
	// True on a baseline beat, false on a burst one, and it means two things
	// that are the same thing: persist a metrics row, and trust every field
	// here.
	//
	// A burst beat carries only what changes between beats — the metrics and
	// GPU utilisation — and omits ports, filesystems and GPU processes, which
	// do not change every fifteen seconds and cost far more to collect and to
	// send than everything else combined. A beat that reports them is around
	// 3.2KB; one that does not is 205 bytes.
	//
	// So the server must merge rather than replace: on a burst beat, the fields
	// it does not carry keep their previous values. It cannot work this out
	// from the message, because proto3 cannot tell an empty repeated field from
	// an absent one — a host with no listening ports and a beat that did not
	// look are identical on the wire. This flag is the only thing that
	// distinguishes them.
	//
	// The consequence, which is deliberate: a machine that stops listening on
	// every port keeps showing its old ports until the next baseline beat, at
	// most two minutes later. Idle detection is unaffected — it only ever runs
	// on beats where this is true.
	RequireDbSave      bool          `protobuf:"varint,7,opt,name=require_db_save,json=requireDbSave,proto3" json:"require_db_save,omitempty"`
	GpuProcesses       []*GpuProcess `protobuf:"bytes,8,rep,name=gpu_processes,json=gpuProcesses,proto3" json:"gpu_processes,omitempty"`
	DiagnosticSnapshot string        `protobuf:"bytes,9,opt,name=diagnostic_snapshot,json=diagnosticSnapshot,proto3" json:"diagnostic_snapshot,omitempty"` // Text snapshot produced by the diagnose command
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_envsight_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{3}
}

func (x *NodeState) GetAgentUuid() string {
	if x != nil {
		return x.AgentUuid
	}
	return ""
}

func (x *NodeState) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *NodeState) GetPorts() []*PortInfo {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *NodeState) GetGpus() []*GpuInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *NodeState) GetHasPhysicalTty() bool {
	if x != nil {
		return x.HasPhysicalTty
	}
	return false
}

func (x *NodeState) GetRequireDbSave() bool {
	if x != nil {
		return x.RequireDbSave
	}
	return false
}

func (x *NodeState) GetGpuProcesses() []*GpuProcess {
	if x != nil {
		return x.GpuProcesses
	}
	return nil
}

func (x *NodeState) GetDiagnosticSnapshot() string {
	if x != nil {
		return x.DiagnosticSnapshot
	}
	return ""
}

// Metrics is one machine's reading at one instant.
//
// Everything added after field 8 is `optional`, and deliberately so. proto3
// cannot tell a zero from an absent value in a plain scalar, and for every one
// of these fields zero is a reading a machine genuinely produces: no network
// traffic, no steal, no swap in use. Without explicit presence:
//
//   - the agent's first beat, which has no previous counter to subtract from,
//     would report 0 B/s — a host saturating its link would draw as idle;
//   - the server could not tell an agent too old to send a field from a new
//     one reporting zero, and would chart a flat line along the floor for
//     every machine that has not been upgraded yet.
//
// One presence bit per field, against roughly 8KB per agent per day. The
// wrong-looking chart costs more.
type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemUsedMb     uint64                 `protobuf:"varint,2,opt,name=mem_used_mb,json=memUsedMb,proto3" json:"mem_used_mb,omitempty"`
	MemTotalMb    uint64                 `protobuf:"varint,3,opt,name=mem_total_mb,json=memTotalMb,proto3" json:"mem_total_mb,omitempty"` // Kept for backward compat and quick percentage calc
	DiskUsedMb    uint64                 `protobuf:"varint,4,opt,name=disk_used_mb,json=diskUsedMb,proto3" json:"disk_used_mb,omitempty"`
	UptimeSeconds uint64                 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Load_1        float64                `protobuf:"fixed64,6,opt,name=load_1,json=load1,proto3" json:"load_1,omitempty"`
	Load_5        float64                `protobuf:"fixed64,7,opt,name=load_5,json=load5,proto3" json:"load_5,omitempty"`
	Load_15       float64                `protobuf:"fixed64,8,opt,name=load_15,json=load15,proto3" json:"load_15,omitempty"`
	// Time the hypervisor gave to somebody else. On a cloud host this is the
	// only evidence that slowness is the neighbour's fault and not the
	// application's — the guest sees low utilisation and high latency, and
	// nothing else in this message explains it.
	CpuStealPercent *float64 `protobuf:"fixed64,9,opt,name=cpu_steal_percent,json=cpuStealPercent,proto3,oneof" json:"cpu_steal_percent,omitempty"`
	// Time blocked on I/O. High iowait alongside high disk_await_ms is the
	// difference between "the CPU is busy" and "the CPU is waiting for a disk".
	CpuIowaitPercent *float64 `protobuf:"fixed64,10,opt,name=cpu_iowait_percent,json=cpuIowaitPercent,proto3,oneof" json:"cpu_iowait_percent,omitempty"`
	// What the kernel believes can still be allocated without swapping. Reported
	// alongside mem_used_mb rather than replacing it: "used" is computed
	// differently on every platform and counts caches the kernel would happily
	// drop, so it answers a different question than "is this host under memory
	// pressure".
	MemAvailableMb *uint64 `protobuf:"varint,11,opt,name=mem_available_mb,json=memAvailableMb,proto3,oneof" json:"mem_available_mb,omitempty"`
	// A host that has started swapping is a host in trouble, and mem_used_mb
	// shows none of it.
	SwapUsedMb *uint64 `protobuf:"varint,12,opt,name=swap_used_mb,json=swapUsedMb,proto3,oneof" json:"swap_used_mb,omitempty"`
	// Inodes on the root filesystem. The classic cause of "the disk is not full
	// but writes fail", and invisible in every byte-based measure. Free: it
	// comes back from the same statfs that fills disk_used_mb.
	DiskInodesPercent *float64 `protobuf:"fixed64,15,opt,name=disk_inodes_percent,json=diskInodesPercent,proto3,oneof" json:"disk_inodes_percent,omitempty"`
	// Share of the interval the device had I/O in flight — what `iostat -x`
	// calls %util. Throughput alone cannot distinguish an idle disk from a
	// saturated one: 5 MB/s is nothing for an NVMe and everything for a tired
	// spindle. Known limitation: on devices with deep queues this saturates at
	// 100% before the device does, which is why await travels with it.
	DiskUtilPercent *float64 `protobuf:"fixed64,16,opt,name=disk_util_percent,json=diskUtilPercent,proto3,oneof" json:"disk_util_percent,omitempty"`
	// Mean wait per I/O. The number that actually says a disk is the
	// bottleneck.
	DiskAwaitMs  *float64 `protobuf:"fixed64,17,opt,name=disk_await_ms,json=diskAwaitMs,proto3,oneof" json:"disk_await_ms,omitempty"`
	DiskReadBps  *float64 `protobuf:"fixed64,18,opt,name=disk_read_bps,json=diskReadBps,proto3,oneof" json:"disk_read_bps,omitempty"`
	DiskWriteBps *float64 `protobuf:"fixed64,19,opt,name=disk_write_bps,json=diskWriteBps,proto3,oneof" json:"disk_write_bps,omitempty"`
	// --- Network -------------------------------------------------------------
	// Physical interfaces only. Loopback would count local traffic that never
	// leaves the host, and container bridges (docker0, br-*, veth*) count the
	// same packets twice — once on the bridge and once on the interface behind
	// it. Which interfaces were summed is not carried here; a host where the
	// answer is surprising is a host with bridges, and NodeState.filesystems is
	// not the place to explain it either.
	NetRxBps *float64 `protobuf:"fixed64,20,opt,name=net_rx_bps,json=netRxBps,proto3,oneof" json:"net_rx_bps,omitempty"`
	NetTxBps *float64 `protobuf:"fixed64,21,opt,name=net_tx_bps,json=netTxBps,proto3,oneof" json:"net_tx_bps,omitempty"`
	// A count that changes shape when something is wrong: a leak that forks
	// without reaping, or a service restarting in a loop. Free — it comes off
	// /proc/loadavg with the numbers below.
	ProcessCount *uint32 `protobuf:"varint,22,opt,name=process_count,json=processCount,proto3,oneof" json:"process_count,omitempty"`
	// Processes in uninterruptible sleep: stuck on I/O that cannot be
	// interrupted, usually a disk or an NFS mount. They cannot be killed —
	// kill -9 does nothing, because the signal is delivered on the way back to
	// userspace and they never get there.
	//
	// This is the field that disambiguates load average, which on Linux counts
	// these processes as well as runnable ones. A load of 50 means either
	//
	//	cpu 95%, blocked 0   — saturated, and behaving normally
	//	cpu  3%, blocked 48  — storage is wedged and nothing can be killed
	//
	// and nothing else in this message tells the two apart. Alongside
	// cpu_iowait_percent and disk_await_ms it completes the picture: how much
	// the CPU waits, how slow the device is, and how many processes are stuck.
	ProcsBlocked  *uint32 `protobuf:"varint,26,opt,name=procs_blocked,json=procsBlocked,proto3,oneof" json:"procs_blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_envsight_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{4}
}

func (x *Metrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Metrics) GetMemUsedMb() uint64 {
	if x != nil {
		return x.MemUsedMb
	}
	return 0
}

func (x *Metrics) GetMemTotalMb() uint64 {
	if x != nil {
		return x.MemTotalMb
	}
	return 0
}

func (x *Metrics) GetDiskUsedMb() uint64 {
	if x != nil {
		return x.DiskUsedMb
	}
	return 0
}

func (x *Metrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Metrics) GetLoad_1() float64 {
	if x != nil {
		return x.Load_1
	}
	return 0
}

func (x *Metrics) GetLoad_5() float64 {
	if x != nil {
		return x.Load_5
	}
	return 0
}

func (x *Metrics) GetLoad_15() float64 {
	if x != nil {
		return x.Load_15
	}
	return 0
}

func (x *Metrics) GetCpuStealPercent() float64 {
	if x != nil && x.CpuStealPercent != nil {
		return *x.CpuStealPercent
	}
	return 0
}

func (x *Metrics) GetCpuIowaitPercent() float64 {
	if x != nil && x.CpuIowaitPercent != nil {
		return *x.CpuIowaitPercent
	}
	return 0
}

func (x *Metrics) GetMemAvailableMb() uint64 {
	if x != nil && x.MemAvailableMb != nil {
		return *x.MemAvailableMb
	}
	return 0
}

func (x *Metrics) GetSwapUsedMb() uint64 {
	if x != nil && x.SwapUsedMb != nil {
		return *x.SwapUsedMb
	}
	return 0
}

func (x *Metrics) GetDiskInodesPercent() float64 {
	if x != nil && x.DiskInodesPercent != nil {
		return *x.DiskInodesPercent
	}
	return 0
}

func (x *Metrics) GetDiskUtilPercent() float64 {
	if x != nil && x.DiskUtilPercent != nil {
		return *x.DiskUtilPercent
	}
	return 0
}

func (x *Metrics) GetDiskAwaitMs() float64 {
	if x != nil && x.DiskAwaitMs != nil {
		return *x.DiskAwaitMs
	}
	return 0
}

func (x *Metrics) GetDiskReadBps() float64 {
	if x != nil && x.DiskReadBps != nil {
		return *x.DiskReadBps
	}
	return 0
}

func (x *Metrics) GetDiskWriteBps() float64 {
	if x != nil && x.DiskWriteBps != nil {
		return *x.DiskWriteBps
	}
	return 0
}

func (x *Metrics) GetNetRxBps() float64 {
	if x != nil && x.NetRxBps != nil {
		return *x.NetRxBps
	}
	return 0
}

func (x *Metrics) GetNetTxBps() float64 {
	if x != nil && x.NetTxBps != nil {
		return *x.NetTxBps
	}
	return 0
}

func (x *Metrics) GetProcessCount() uint32 {
	if x != nil && x.ProcessCount != nil {
		return *x.ProcessCount
	}
	return 0
}

func (x *Metrics) GetProcsBlocked() uint32 {
	if x != nil && x.ProcsBlocked != nil {
		return *x.ProcsBlocked
	}
	return 0
}

type GpuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	UsagePercent  float32                `protobuf:"fixed32,3,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	VramTotalMb   uint64                 `protobuf:"varint,4,opt,name=vram_total_mb,json=vramTotalMb,proto3" json:"vram_total_mb,omitempty"`
	VramUsedMb    uint64                 `protobuf:"varint,5,opt,name=vram_used_mb,json=vramUsedMb,proto3" json:"vram_used_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuInfo) Reset() {
	*x = GpuInfo{}
	mi := &file_envsight_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuInfo) ProtoMessage() {}

func (x *GpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuInfo.ProtoReflect.Descriptor instead.
func (*GpuInfo) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{5}
}

func (x *GpuInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GpuInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GpuInfo) GetUsagePercent() float32 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *GpuInfo) GetVramTotalMb() uint64 {
	if x != nil {
		return x.VramTotalMb
	}
	return 0
}

func (x *GpuInfo) GetVramUsedMb() uint64 {
	if x != nil {
		return x.VramUsedMb
	}
	return 0
}

type GpuProcess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ProcessName   string                 `protobuf:"bytes,2,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"` // User running the process
	VramUsedMb    uint64                 `protobuf:"varint,4,opt,name=vram_used_mb,json=vramUsedMb,proto3" json:"vram_used_mb,omitempty"`
	GpuIndex      uint32                 `protobuf:"varint,5,opt,name=gpu_index,json=gpuIndex,proto3" json:"gpu_index,omitempty"` // Which GPU this process is running on
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuProcess) Reset() {
	*x = GpuProcess{}
	mi := &file_envsight_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuProcess) ProtoMessage() {}

func (x *GpuProcess) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuProcess.ProtoReflect.Descriptor instead.
func (*GpuProcess) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{6}
}

func (x *GpuProcess) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *GpuProcess) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *GpuProcess) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GpuProcess) GetVramUsedMb() uint64 {
	if x != nil {
		return x.VramUsedMb
	}
	return 0
}

func (x *GpuProcess) GetGpuIndex() uint32 {
	if x != nil {
		return x.GpuIndex
	}
	return 0
}

type PortInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	ProcessName   string                 `protobuf:"bytes,2,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Cmdline       string                 `protobuf:"bytes,3,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"` // User running the process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortInfo) Reset() {
	*x = PortInfo{}
	mi := &file_envsight_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortInfo) ProtoMessage() {}

func (x *PortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortInfo.ProtoReflect.Descriptor instead.
func (*PortInfo) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{7}
}

func (x *PortInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortInfo) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *PortInfo) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *PortInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ServerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // e.g. "request_detail", "diagnose"
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_envsight_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{8}
}

func (x *ServerCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ServerCommand) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_envsight_proto protoreflect.FileDescriptor

const file_envsight_proto_rawDesc = "" +
	"\n" +
	"\x0eenvsight.proto\x12\benvsight\"w\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"agent_uuid\x18\x01 \x01(\tR\tagentUuid\x12/\n" +
	"\thost_info\x18\x02 \x01(\v2\x12.envsight.HostInfoR\bhostInfo\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\xaa\x01\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"agent_uuid\x18\x01 \x01(\tR\tagentUuid\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12.\n" +
	"\x10agent_credential\x18\x04 \x01(\tH\x00R\x0fagentCredential\x88\x01\x01B\x13\n" +
	"\x11_agent_credential\"\xcc\x02\n" +
	"\bHostInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_info\x18\x02 \x01(\tR\x06osInfo\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\x05R\bcpuCores\x12 \n" +
	"\fmem_total_mb\x18\x05 \x01(\x04R\n" +
	"memTotalMb\x12\"\n" +
	"\rdisk_total_mb\x18\x06 \x01(\x04R\vdiskTotalMb\x12%\n" +
	"\x04gpus\x18\a \x03(\v2\x11.envsight.GpuInfoR\x04gpus\x12%\n" +
	"\x0ecloud_provider\x18\b \x01(\tR\rcloudProvider\x12'\n" +
	"\rswap_total_mb\x18\t \x01(\x04H\x00R\vswapTotalMb\x88\x01\x01B\x10\n" +
	"\x0e_swap_total_mb\"\x88\x03\n" +
	"\tNodeState\x12\x1d\n" +
	"\n" +
	"agent_uuid\x18\x01 \x01(\tR\tagentUuid\x12+\n" +
	"\ametrics\x18\x02 \x01(\v2\x11.envsight.MetricsR\ametrics\x12(\n" +
	"\x05ports\x18\x03 \x03(\v2\x12.envsight.PortInfoR\x05ports\x12%\n" +
	"\x04gpus\x18\x04 \x03(\v2\x11.envsight.GpuInfoR\x04gpus\x12(\n" +
	"\x10has_physical_tty\x18\x05 \x01(\bR\x0ehasPhysicalTty\x12&\n" +
	"\x0frequire_db_save\x18\a \x01(\bR\rrequireDbSave\x129\n" +
	"\rgpu_processes\x18\b \x03(\v2\x14.envsight.GpuProcessR\fgpuProcesses\x12/\n" +
	"\x13diagnostic_snapshot\x18\t \x01(\tR\x12diagnosticSnapshotJ\x04\b\x06\x10\aJ\x04\b\n" +
	"\x10\vR\ais_idleR\vfilesystems\"\xa3\t\n" +
	"\aMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1e\n" +
	"\vmem_used_mb\x18\x02 \x01(\x04R\tmemUsedMb\x12 \n" +
	"\fmem_total_mb\x18\x03 \x01(\x04R\n" +
	"memTotalMb\x12 \n" +
	"\fdisk_used_mb\x18\x04 \x01(\x04R\n" +
	"diskUsedMb\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04R\ruptimeSeconds\x12\x15\n" +
	"\x06load_1\x18\x06 \x01(\x01R\x05load1\x12\x15\n" +
	"\x06load_5\x18\a \x01(\x01R\x05load5\x12\x17\n" +
	"\aload_15\x18\b \x01(\x01R\x06load15\x12/\n" +
	"\x11cpu_steal_percent\x18\t \x01(\x01H\x00R\x0fcpuStealPercent\x88\x01\x01\x121\n" +
	"\x12cpu_iowait_percent\x18\n" +
	" \x01(\x01H\x01R\x10cpuIowaitPercent\x88\x01\x01\x12-\n" +
	"\x10mem_available_mb\x18\v \x01(\x04H\x02R\x0ememAvailableMb\x88\x01\x01\x12%\n" +
	"\fswap_used_mb\x18\f \x01(\x04H\x03R\n" +
	"swapUsedMb\x88\x01\x01\x123\n" +
	"\x13disk_inodes_percent\x18\x0f \x01(\x01H\x04R\x11diskInodesPercent\x88\x01\x01\x12/\n" +
	"\x11disk_util_percent\x18\x10 \x01(\x01H\x05R\x0fdiskUtilPercent\x88\x01\x01\x12'\n" +
	"\rdisk_await_ms\x18\x11 \x01(\x01H\x06R\vdiskAwaitMs\x88\x01\x01\x12'\n" +
	"\rdisk_read_bps\x18\x12 \x01(\x01H\aR\vdiskReadBps\x88\x01\x01\x12)\n" +
	"\x0edisk_write_bps\x18\x13 \x01(\x01H\bR\fdiskWriteBps\x88\x01\x01\x12!\n" +
	"\n" +
	"net_rx_bps\x18\x14 \x01(\x01H\tR\bnetRxBps\x88\x01\x01\x12!\n" +
	"\n" +
	"net_tx_bps\x18\x15 \x01(\x01H\n" +
	"R\bnetTxBps\x88\x01\x01\x12(\n" +
	"\rprocess_count\x18\x16 \x01(\rH\vR\fprocessCount\x88\x01\x01\x12(\n" +
	"\rprocs_blocked\x18\x1a \x01(\rH\fR\fprocsBlocked\x88\x01\x01B\x14\n" +
	"\x12_cpu_steal_percentB\x15\n" +
	"\x13_cpu_iowait_percentB\x13\n" +
	"\x11_mem_available_mbB\x0f\n" +
	"\r_swap_used_mbB\x16\n" +
	"\x14_disk_inodes_percentB\x14\n" +
	"\x12_disk_util_percentB\x10\n" +
	"\x0e_disk_await_msB\x10\n" +
	"\x0e_disk_read_bpsB\x11\n" +
	"\x0f_disk_write_bpsB\r\n" +
	"\v_net_rx_bpsB\r\n" +
	"\v_net_tx_bpsB\x10\n" +
	"\x0e_process_countB\x10\n" +
	"\x0e_procs_blockedJ\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fJ\x04\b\x17\x10\x18J\x04\b\x18\x10\x19J\x04\b\x19\x10\x1aR\x14disk_fullest_percentR\x12disk_fullest_mountR\fthread_countR\x0ftcp_establishedR\rtcp_time_wait\"\xa2\x01\n" +
	"\aGpuInfo\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rusage_percent\x18\x03 \x01(\x02R\fusagePercent\x12\"\n" +
	"\rvram_total_mb\x18\x04 \x01(\x04R\vvramTotalMb\x12 \n" +
	"\fvram_used_mb\x18\x05 \x01(\x04R\n" +
	"vramUsedMb\"\x94\x01\n" +
	"\n" +
	"GpuProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12!\n" +
	"\fprocess_name\x18\x02 \x01(\tR\vprocessName\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12 \n" +
	"\fvram_used_mb\x18\x04 \x01(\x04R\n" +
	"vramUsedMb\x12\x1b\n" +
	"\tgpu_index\x18\x05 \x01(\rR\bgpuIndex\"o\n" +
	"\bPortInfo\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12!\n" +
	"\fprocess_name\x18\x02 \x01(\tR\vprocessName\x12\x18\n" +
	"\acmdline\x18\x03 \x01(\tR\acmdline\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"A\n" +
	"\rServerCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload2\x93\x01\n" +
	"\fAgentService\x12A\n" +
	"\bRegister\x12\x19.envsight.RegisterRequest\x1a\x1a.envsight.RegisterResponse\x12@\n" +
	"\fStreamStatus\x12\x13.envsight.NodeState\x1a\x17.envsight.ServerCommand(\x010\x01B(Z&github.com/EnvSight/envsight-api/pb;pbb\x06proto3"

var (
	file_envsight_proto_rawDescOnce sync.Once
	file_envsight_proto_rawDescData []byte
)

func file_envsight_proto_rawDescGZIP() []byte {
	file_envsight_proto_rawDescOnce.Do(func() {
		file_envsight_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envsight_proto_rawDesc), len(file_envsight_proto_rawDesc)))
	})
	return file_envsight_proto_rawDescData
}

var file_envsight_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_envsight_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: envsight.RegisterRequest
	(*RegisterResponse)(nil), // 1: envsight.RegisterResponse
	(*HostInfo)(nil),         // 2: envsight.HostInfo
	(*NodeState)(nil),        // 3: envsight.NodeState
	(*Metrics)(nil),          // 4: envsight.Metrics
	(*GpuInfo)(nil),          // 5: envsight.GpuInfo
	(*GpuProcess)(nil),       // 6: envsight.GpuProcess
	(*PortInfo)(nil),         // 7: envsight.PortInfo
	(*ServerCommand)(nil),    // 8: envsight.ServerCommand
}
var file_envsight_proto_depIdxs = []int32{
	2, // 0: envsight.RegisterRequest.host_info:type_name -> envsight.HostInfo
	5, // 1: envsight.HostInfo.gpus:type_name -> envsight.GpuInfo
	4, // 2: envsight.NodeState.metrics:type_name -> envsight.Metrics
	7, // 3: envsight.NodeState.ports:type_name -> envsight.PortInfo
	5, // 4: envsight.NodeState.gpus:type_name -> envsight.GpuInfo
	6, // 5: envsight.NodeState.gpu_processes:type_name -> envsight.GpuProcess
	0, // 6: envsight.AgentService.Register:input_type -> envsight.RegisterRequest
	3, // 7: envsight.AgentService.StreamStatus:input_type -> envsight.NodeState
	1, // 8: envsight.AgentService.Register:output_type -> envsight.RegisterResponse
	8, // 9: envsight.AgentService.StreamStatus:output_type -> envsight.ServerCommand
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_envsight_proto_init() }
func file_envsight_proto_init() {
	if File_envsight_proto != nil {
		return
	}
	file_envsight_proto_msgTypes[1].OneofWrappers = []any{}
	file_envsight_proto_msgTypes[2].OneofWrappers = []any{}
	file_envsight_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envsight_proto_rawDesc), len(file_envsight_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_envsight_proto_goTypes,
		DependencyIndexes: file_envsight_proto_depIdxs,
		MessageInfos:      file_envsight_proto_msgTypes,
	}.Build()
	File_envsight_proto = out.File
	file_envsight_proto_goTypes = nil
	file_envsight_proto_depIdxs = nil
}
