// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: envsight.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentUuid     string                 `protobuf:"bytes,1,opt,name=agent_uuid,json=agentUuid,proto3" json:"agent_uuid,omitempty"` // Empty on first registration; cached UUID otherwise
	HostInfo      *HostInfo              `protobuf:"bytes,2,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`    // Static host inventory collected at startup
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                          // Agent API token (also sent as gRPC Bearer metadata)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_envsight_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentUuid() string {
	if x != nil {
		return x.AgentUuid
	}
	return ""
}

func (x *RegisterRequest) GetHostInfo() *HostInfo {
	if x != nil {
		return x.HostInfo
	}
	return nil
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentUuid     string                 `protobuf:"bytes,1,opt,name=agent_uuid,json=agentUuid,proto3" json:"agent_uuid,omitempty"` // Server-issued or confirmed UUID
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Error description when success == false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_envsight_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAgentUuid() string {
	if x != nil {
		return x.AgentUuid
	}
	return ""
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HostInfo carries the static, rarely-changing facts about a machine.
type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsInfo        string                 `protobuf:"bytes,2,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Optional cloud provider instance ID
	CpuCores      int32                  `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemTotalMb    uint64                 `protobuf:"varint,5,opt,name=mem_total_mb,json=memTotalMb,proto3" json:"mem_total_mb,omitempty"`
	DiskTotalMb   uint64                 `protobuf:"varint,6,opt,name=disk_total_mb,json=diskTotalMb,proto3" json:"disk_total_mb,omitempty"`
	Gpus          []*GpuInfo             `protobuf:"bytes,7,rep,name=gpus,proto3" json:"gpus,omitempty"`
	CloudProvider string                 `protobuf:"bytes,8,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_envsight_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{2}
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetOsInfo() string {
	if x != nil {
		return x.OsInfo
	}
	return ""
}

func (x *HostInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HostInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HostInfo) GetMemTotalMb() uint64 {
	if x != nil {
		return x.MemTotalMb
	}
	return 0
}

func (x *HostInfo) GetDiskTotalMb() uint64 {
	if x != nil {
		return x.DiskTotalMb
	}
	return 0
}

func (x *HostInfo) GetGpus() []*GpuInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *HostInfo) GetCloudProvider() string {
	if x != nil {
		return x.CloudProvider
	}
	return ""
}

// NodeState is the dynamic per-heartbeat payload streamed by the agent.
type NodeState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentUuid          string                 `protobuf:"bytes,1,opt,name=agent_uuid,json=agentUuid,proto3" json:"agent_uuid,omitempty"`
	Metrics            *Metrics               `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Ports              []*PortInfo            `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	Gpus               []*GpuInfo             `protobuf:"bytes,4,rep,name=gpus,proto3" json:"gpus,omitempty"` // GPU usage may change dynamically
	HasPhysicalTty     bool                   `protobuf:"varint,5,opt,name=has_physical_tty,json=hasPhysicalTty,proto3" json:"has_physical_tty,omitempty"`
	IsIdle             bool                   `protobuf:"varint,6,opt,name=is_idle,json=isIdle,proto3" json:"is_idle,omitempty"`                        // Agent-side idle detection flag
	RequireDbSave      bool                   `protobuf:"varint,7,opt,name=require_db_save,json=requireDbSave,proto3" json:"require_db_save,omitempty"` // When true, server persists a SysMetric row
	GpuProcesses       []*GpuProcess          `protobuf:"bytes,8,rep,name=gpu_processes,json=gpuProcesses,proto3" json:"gpu_processes,omitempty"`
	DiagnosticSnapshot string                 `protobuf:"bytes,9,opt,name=diagnostic_snapshot,json=diagnosticSnapshot,proto3" json:"diagnostic_snapshot,omitempty"` // Text snapshot produced by the diagnose command
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_envsight_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{3}
}

func (x *NodeState) GetAgentUuid() string {
	if x != nil {
		return x.AgentUuid
	}
	return ""
}

func (x *NodeState) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *NodeState) GetPorts() []*PortInfo {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *NodeState) GetGpus() []*GpuInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *NodeState) GetHasPhysicalTty() bool {
	if x != nil {
		return x.HasPhysicalTty
	}
	return false
}

func (x *NodeState) GetIsIdle() bool {
	if x != nil {
		return x.IsIdle
	}
	return false
}

func (x *NodeState) GetRequireDbSave() bool {
	if x != nil {
		return x.RequireDbSave
	}
	return false
}

func (x *NodeState) GetGpuProcesses() []*GpuProcess {
	if x != nil {
		return x.GpuProcesses
	}
	return nil
}

func (x *NodeState) GetDiagnosticSnapshot() string {
	if x != nil {
		return x.DiagnosticSnapshot
	}
	return ""
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemUsedMb     uint64                 `protobuf:"varint,2,opt,name=mem_used_mb,json=memUsedMb,proto3" json:"mem_used_mb,omitempty"`
	MemTotalMb    uint64                 `protobuf:"varint,3,opt,name=mem_total_mb,json=memTotalMb,proto3" json:"mem_total_mb,omitempty"` // Kept for backward compat and quick percentage calc
	DiskUsedMb    uint64                 `protobuf:"varint,4,opt,name=disk_used_mb,json=diskUsedMb,proto3" json:"disk_used_mb,omitempty"`
	UptimeSeconds uint64                 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Load_1        float64                `protobuf:"fixed64,6,opt,name=load_1,json=load1,proto3" json:"load_1,omitempty"`
	Load_5        float64                `protobuf:"fixed64,7,opt,name=load_5,json=load5,proto3" json:"load_5,omitempty"`
	Load_15       float64                `protobuf:"fixed64,8,opt,name=load_15,json=load15,proto3" json:"load_15,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_envsight_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{4}
}

func (x *Metrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Metrics) GetMemUsedMb() uint64 {
	if x != nil {
		return x.MemUsedMb
	}
	return 0
}

func (x *Metrics) GetMemTotalMb() uint64 {
	if x != nil {
		return x.MemTotalMb
	}
	return 0
}

func (x *Metrics) GetDiskUsedMb() uint64 {
	if x != nil {
		return x.DiskUsedMb
	}
	return 0
}

func (x *Metrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Metrics) GetLoad_1() float64 {
	if x != nil {
		return x.Load_1
	}
	return 0
}

func (x *Metrics) GetLoad_5() float64 {
	if x != nil {
		return x.Load_5
	}
	return 0
}

func (x *Metrics) GetLoad_15() float64 {
	if x != nil {
		return x.Load_15
	}
	return 0
}

type GpuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	UsagePercent  float32                `protobuf:"fixed32,3,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	VramTotalMb   uint64                 `protobuf:"varint,4,opt,name=vram_total_mb,json=vramTotalMb,proto3" json:"vram_total_mb,omitempty"`
	VramUsedMb    uint64                 `protobuf:"varint,5,opt,name=vram_used_mb,json=vramUsedMb,proto3" json:"vram_used_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuInfo) Reset() {
	*x = GpuInfo{}
	mi := &file_envsight_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuInfo) ProtoMessage() {}

func (x *GpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuInfo.ProtoReflect.Descriptor instead.
func (*GpuInfo) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{5}
}

func (x *GpuInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GpuInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GpuInfo) GetUsagePercent() float32 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *GpuInfo) GetVramTotalMb() uint64 {
	if x != nil {
		return x.VramTotalMb
	}
	return 0
}

func (x *GpuInfo) GetVramUsedMb() uint64 {
	if x != nil {
		return x.VramUsedMb
	}
	return 0
}

type GpuProcess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ProcessName   string                 `protobuf:"bytes,2,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"` // User running the process
	VramUsedMb    uint64                 `protobuf:"varint,4,opt,name=vram_used_mb,json=vramUsedMb,proto3" json:"vram_used_mb,omitempty"`
	GpuIndex      uint32                 `protobuf:"varint,5,opt,name=gpu_index,json=gpuIndex,proto3" json:"gpu_index,omitempty"` // Which GPU this process is running on
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuProcess) Reset() {
	*x = GpuProcess{}
	mi := &file_envsight_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuProcess) ProtoMessage() {}

func (x *GpuProcess) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuProcess.ProtoReflect.Descriptor instead.
func (*GpuProcess) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{6}
}

func (x *GpuProcess) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *GpuProcess) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *GpuProcess) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *GpuProcess) GetVramUsedMb() uint64 {
	if x != nil {
		return x.VramUsedMb
	}
	return 0
}

func (x *GpuProcess) GetGpuIndex() uint32 {
	if x != nil {
		return x.GpuIndex
	}
	return 0
}

type PortInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	ProcessName   string                 `protobuf:"bytes,2,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Cmdline       string                 `protobuf:"bytes,3,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"` // User running the process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortInfo) Reset() {
	*x = PortInfo{}
	mi := &file_envsight_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortInfo) ProtoMessage() {}

func (x *PortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortInfo.ProtoReflect.Descriptor instead.
func (*PortInfo) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{7}
}

func (x *PortInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortInfo) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *PortInfo) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *PortInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ServerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // e.g. "request_detail", "diagnose"
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_envsight_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_envsight_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_envsight_proto_rawDescGZIP(), []int{8}
}

func (x *ServerCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ServerCommand) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_envsight_proto protoreflect.FileDescriptor

const file_envsight_proto_rawDesc = "" +
	"\n" +
	"\x0eenvsight.proto\x12\benvsight\"w\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"agent_uuid\x18\x01 \x01(\tR\tagentUuid\x12/\n" +
	"\thost_info\x18\x02 \x01(\v2\x12.envsight.HostInfoR\bhostInfo\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"e\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"agent_uuid\x18\x01 \x01(\tR\tagentUuid\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x91\x02\n" +
	"\bHostInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_info\x18\x02 \x01(\tR\x06osInfo\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\x05R\bcpuCores\x12 \n" +
	"\fmem_total_mb\x18\x05 \x01(\x04R\n" +
	"memTotalMb\x12\"\n" +
	"\rdisk_total_mb\x18\x06 \x01(\x04R\vdiskTotalMb\x12%\n" +
	"\x04gpus\x18\a \x03(\v2\x11.envsight.GpuInfoR\x04gpus\x12%\n" +
	"\x0ecloud_provider\x18\b \x01(\tR\rcloudProvider\"\xff\x02\n" +
	"\tNodeState\x12\x1d\n" +
	"\n" +
	"agent_uuid\x18\x01 \x01(\tR\tagentUuid\x12+\n" +
	"\ametrics\x18\x02 \x01(\v2\x11.envsight.MetricsR\ametrics\x12(\n" +
	"\x05ports\x18\x03 \x03(\v2\x12.envsight.PortInfoR\x05ports\x12%\n" +
	"\x04gpus\x18\x04 \x03(\v2\x11.envsight.GpuInfoR\x04gpus\x12(\n" +
	"\x10has_physical_tty\x18\x05 \x01(\bR\x0ehasPhysicalTty\x12\x17\n" +
	"\ais_idle\x18\x06 \x01(\bR\x06isIdle\x12&\n" +
	"\x0frequire_db_save\x18\a \x01(\bR\rrequireDbSave\x129\n" +
	"\rgpu_processes\x18\b \x03(\v2\x14.envsight.GpuProcessR\fgpuProcesses\x12/\n" +
	"\x13diagnostic_snapshot\x18\t \x01(\tR\x12diagnosticSnapshot\"\xfc\x01\n" +
	"\aMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1e\n" +
	"\vmem_used_mb\x18\x02 \x01(\x04R\tmemUsedMb\x12 \n" +
	"\fmem_total_mb\x18\x03 \x01(\x04R\n" +
	"memTotalMb\x12 \n" +
	"\fdisk_used_mb\x18\x04 \x01(\x04R\n" +
	"diskUsedMb\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04R\ruptimeSeconds\x12\x15\n" +
	"\x06load_1\x18\x06 \x01(\x01R\x05load1\x12\x15\n" +
	"\x06load_5\x18\a \x01(\x01R\x05load5\x12\x17\n" +
	"\aload_15\x18\b \x01(\x01R\x06load15\"\xa2\x01\n" +
	"\aGpuInfo\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rusage_percent\x18\x03 \x01(\x02R\fusagePercent\x12\"\n" +
	"\rvram_total_mb\x18\x04 \x01(\x04R\vvramTotalMb\x12 \n" +
	"\fvram_used_mb\x18\x05 \x01(\x04R\n" +
	"vramUsedMb\"\x94\x01\n" +
	"\n" +
	"GpuProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12!\n" +
	"\fprocess_name\x18\x02 \x01(\tR\vprocessName\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12 \n" +
	"\fvram_used_mb\x18\x04 \x01(\x04R\n" +
	"vramUsedMb\x12\x1b\n" +
	"\tgpu_index\x18\x05 \x01(\rR\bgpuIndex\"o\n" +
	"\bPortInfo\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12!\n" +
	"\fprocess_name\x18\x02 \x01(\tR\vprocessName\x12\x18\n" +
	"\acmdline\x18\x03 \x01(\tR\acmdline\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"A\n" +
	"\rServerCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload2\x93\x01\n" +
	"\fAgentService\x12A\n" +
	"\bRegister\x12\x19.envsight.RegisterRequest\x1a\x1a.envsight.RegisterResponse\x12@\n" +
	"\fStreamStatus\x12\x13.envsight.NodeState\x1a\x17.envsight.ServerCommand(\x010\x01B*Z(github.com/Moriaty911/envsight-api/pb;pbb\x06proto3"

var (
	file_envsight_proto_rawDescOnce sync.Once
	file_envsight_proto_rawDescData []byte
)

func file_envsight_proto_rawDescGZIP() []byte {
	file_envsight_proto_rawDescOnce.Do(func() {
		file_envsight_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envsight_proto_rawDesc), len(file_envsight_proto_rawDesc)))
	})
	return file_envsight_proto_rawDescData
}

var file_envsight_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_envsight_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: envsight.RegisterRequest
	(*RegisterResponse)(nil), // 1: envsight.RegisterResponse
	(*HostInfo)(nil),         // 2: envsight.HostInfo
	(*NodeState)(nil),        // 3: envsight.NodeState
	(*Metrics)(nil),          // 4: envsight.Metrics
	(*GpuInfo)(nil),          // 5: envsight.GpuInfo
	(*GpuProcess)(nil),       // 6: envsight.GpuProcess
	(*PortInfo)(nil),         // 7: envsight.PortInfo
	(*ServerCommand)(nil),    // 8: envsight.ServerCommand
}
var file_envsight_proto_depIdxs = []int32{
	2, // 0: envsight.RegisterRequest.host_info:type_name -> envsight.HostInfo
	5, // 1: envsight.HostInfo.gpus:type_name -> envsight.GpuInfo
	4, // 2: envsight.NodeState.metrics:type_name -> envsight.Metrics
	7, // 3: envsight.NodeState.ports:type_name -> envsight.PortInfo
	5, // 4: envsight.NodeState.gpus:type_name -> envsight.GpuInfo
	6, // 5: envsight.NodeState.gpu_processes:type_name -> envsight.GpuProcess
	0, // 6: envsight.AgentService.Register:input_type -> envsight.RegisterRequest
	3, // 7: envsight.AgentService.StreamStatus:input_type -> envsight.NodeState
	1, // 8: envsight.AgentService.Register:output_type -> envsight.RegisterResponse
	8, // 9: envsight.AgentService.StreamStatus:output_type -> envsight.ServerCommand
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_envsight_proto_init() }
func file_envsight_proto_init() {
	if File_envsight_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envsight_proto_rawDesc), len(file_envsight_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_envsight_proto_goTypes,
		DependencyIndexes: file_envsight_proto_depIdxs,
		MessageInfos:      file_envsight_proto_msgTypes,
	}.Build()
	File_envsight_proto = out.File
	file_envsight_proto_goTypes = nil
	file_envsight_proto_depIdxs = nil
}
